create table test04(
    mid NUMBER GENERATED AS IDENTITY primary key, -- 시퀀스 자동기입
    mname VARCHAR2(20)
);

INSERT INTO test04 (mname) VALUES('James');
INSERT INTO test04 (mname) VALUES('James2');
INSERT INTO test04 (mname) VALUES('James3');
delete from test04 where mid = 3;
INSERT INTO test04 (mname) VALUES('James4');
insert into test04 (mid,mname) values(100,'Hong'); -- 시퀀스 값 직접 삽입 불가

select * from test04;

create table test05(
    mid NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 100 INCREMENT BY 10)
        PRIMARY KEY,
    mname VARCHAR2(20)
);

INSERT INTO test05 (mname) values('khan');
INSERT INTO test05 (mname) values('khan2');
INSERT INTO test05 (mid, mname) values(50, 'khan'); -- 시퀀스 값 직접 삽입 가능. by default라서
select * from test05;

