CREATE TABLE sample_member(
    mno NUMBER PRIMARY KEY,
    mname VARCHAR2(20) NOT NULL
);

CREATE SEQUENCE smember_seq
    START WITH 1
    INCREMENT BY 1;
    
INSERT INTO sample_member(mno,mname) 
VALUES(smember_seq.NEXTVAL, 'b');

SELECT * FROM sample_member;

DELETE FROM sample_member WHERE mno = 143;

SELECT smember_seq.NEXTVAL FROM dual;
SELECT smember_seq.CURRVAL FROM dual;

SELECT * FROM USER_SEQUENCES;

DROP SEQUENCE smember_seq2;
CREATE SEQUENCE smember_seq2
    START WITH 1
    INCREMENT BY 1
--    MAXVALUE 10
    NOCYCLE
    CACHE 5;
    
SELECT smember_seq2.NEXTVAL FROM dual;
SELECT smember_seq2.CURRVAL FROM dual;

-- 날짜
SELECT * FROM nls_session_parameters WHERE parameter = 'NLS_DATE_FORMAT';
ALTER SESSION SET nls_date_format = 'YYYY-MM-DD HH24:MI:SS';

SELECT SYSDATE FROM dual;

CREATE TABLE test03(
    d DATE
);

INSERT INTO test03 VALUES ('2026-09-15');
INSERT INTO test03 VALUES ('2026-09-15 10:21:31');
-- 문자열을 날짜 형태의 데이터로 바꿔주는 함수 TO_DATE.. 날짜, 저장될 형식
INSERT INTO test03 VALUES (TO_DATE('2026-09-15 10:21:31', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO test03 VALUES (SYSDATE);

SELECT * FROM test03;


-- 좀더 정밀한 시간이 필요하다면 TIMESTAMP
CREATE TABLE login_history(
    login_id NUMBER,
    login_time TIMESTAMP
);

INSERT INTO login_history VALUES(1,TIMESTAMP '2026-09-15 09:30:25.123456');
SELECT * FROM login_history;

-- with time zone
CREATE TABLE reservation(
    reservation_id NUMBER,
    reservation_time TIMESTAMP WITH TIME ZONE
);

INSERT INTO reservation VALUES(1,TIMESTAMP '2026-09-15 10:00:00 +09:00');
SELECT * FROM reservation;

--DB 서버의 시간
SELECT SYSDATE FROM dual;
--현재 SESSION의 시간
SELECT CURRENT_DATE FROM dual;

--TO_DATE('2026-09-15 10:21:31', 'YYYY-MM-DD HH24:MI:SS')
--TO_CHAR(SYSDATE, 'YYYY/MM/DD')

SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD') FROM dual;

SELECT SYSDATE FROM DUAL;
SELECT SYSDATE + 1 FROM DUAL;
SELECT SYSDATE - 1 FROM DUAL;
SELECT SYSDATE + 1/24 FROM DUAL;
SELECT SYSDATE + 30/1440 FROM DUAL;
--근속 일수
SELECT SYSDATE - TO_DATE('2026-08-20', 'YYYY-MM-DD') FROM DUAL;
SELECT ADD_MONTHS (TO_DATE('2026-01-25','YYYY-MM-DD'),3) FROM DUAL;

SELECT MONTHS_BETWEEN(
    SYSDATE,
    TO_DATE('2026-01-01','YYYY-MM-DD')    
) FROM DUAL;

SELECT LAST_DAY(
    TO_DATE('2026-09-10','YYYY-MM-DD')
)FROM DUAL;

-- 해당날짜부터 가장 빠른 요일의 날짜를 구해줌
SELECT NEXT_DAY(
    TO_DATE('2026-09-15','YYYY-MM-DD'), '월요일'
)FROM DUAL;

SELECT TRUNC(SYSDATE) FROM DUAL;
SELECT TRUNC(SYSDATE, 'MM') FROM DUAL;
-- 내림
SELECT TRUNC(SYSDATE, 'YYYY') FROM DUAL;

SELECT ROUND(SYSDATE) FROM DUAL;
SELECT ROUND(SYSDATE, 'MM') FROM DUAL;
-- 반올림
SELECT ROUND(SYSDATE, 'YYYY') FROM DUAL;
SELECT ROUND(TO_DATE('2026-03-01','YYYY-MM-DD'), 'YYYY') FROM DUAL;

-- AS 뒤에 단어가 별칭을 달고 컬럼으로 쓰인다.
SELECT EXTRACT(YEAR FROM SYSDATE) AS year,
EXTRACT(MONTH FROM SYSDATE) AS month,
EXTRACT(DAY FROM SYSDATE) AS day FROM dual;